stages:
  - build
  - test
  - staging

build-job:
  stage: build
  script:
    - echo "Building the project..."
    - cd app
    - tar -zcvf index.html.tar.gz ./index.html
    - cd ..
    - mkdir target
    - mv app/index.html.tar.gz target/
    - echo "Build completed"
  artifacts:
    paths:
      - target/index.html.tar.gz
    expire_in: 1 day

test-job1:
  stage: test
  script:
    - echo "Testing the project and go to sleep for 2 seconds..."
    - sleep 2
    - echo "Test-job1 completed"

test-job2:
  stage: test
  script:
    - mkdir testing-folder
    - tar -xvzf target/index.html.tar.gz -C testing-folder/
    - chmod u+x test/test-index-contains.sh
    - ./test/test-index-contains.sh
  
configure-application:
  stage: staging
  image:
    name: gitlab.lnu.se:5050/dipeab/2dv013-ht24-ci/myansible:latest
  variables:
    # make sure Ansible uses the repo-root config that points to your inventory/roles
    ANSIBLE_CONFIG: ./ansible.cfg
  before_script:
    - mkdir -p ~/.ssh && chmod 700 ~/.ssh
    # write the PEM from CI vars to a file with correct perms
    - printf "%s\n" "$STAGING_KEY" > ~/.ssh/id_ci
    - chmod 600 ~/.ssh/id_ci
    # optional safety; the ansible.cfg already disables host key checking
    # - printf "Host *\n  StrictHostKeyChecking no\n" > ~/.ssh/config
  script:
    - ansible-playbook deploy/ansible/playbooks/web.yml \
        --extra-vars="ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_ci"
