stages:
  - build
  - test
  - staging

build-job:
  stage: build
  script:
    - echo "Building the project..."
    - cd app
    - tar -zcvf index.html.tar.gz ./index.html
    - cd ..
    - mkdir target
    - mv app/index.html.tar.gz target/
    - echo "Build completed"
  artifacts:
    paths:
      - target/index.html.tar.gz
    expire_in: 1 day

test-job1:
  stage: test
  script:
    - echo "Testing the project and go to sleep for 2 seconds..."
    - sleep 2
    - echo "Test-job1 completed"
test-job2:
  stage: test
  script:
    - mkdir testing-folder
    - tar -xvzf target/index.html.tar.gz -C testing-folder/
    - chmod u+x test/test-index-contains.sh
    - ./test/test-index-contains.sh
