- name: Ensure nginx is installed
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: true
  become: true

# IPv4 listen -> 8080
- name: Set nginx IPv4 listen to {{ web_listen_port | default(8080) }}
  ansible.builtin.replace:
    path: /etc/nginx/sites-available/default
    regexp: 'listen 80 default_server;'
    replace: 'listen {{ web_listen_port | default(8080) }} default_server;'
  notify: Restart nginx
  become: true

# IPv6 listen -> 8080
- name: Set nginx IPv6 listen to {{ web_listen_port | default(8080) }}
  ansible.builtin.replace:
    path: /etc/nginx/sites-available/default
    regexp: 'listen \[::\]:80 default_server;'
    replace: 'listen [::]:{{ web_listen_port | default(8080) }} default_server;'
  notify: Restart nginx
  become: true

- name: Start & enable nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true
  become: true

- name: Deploy website files from repo
  ansible.builtin.copy:
    src: "{{ app_src }}"
    dest: /var/www/html/
    owner: root
    group: root
    mode: "0644"
    directory_mode: "0755"
  notify: Restart nginx
  become: true

# Adding inline content directly instead of deploying files
# - name: Place index page
#  ansible.builtin.copy:
#    dest: /var/www/html/index.html
#    content: |
#      <h1>Hello from Ansible</h1>
#      <p>Served via nginx on port {{ web_listen_port | default(8080) }}.</p>
#  become: true

